# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  branches:
    develop:
    - step:
        name: Setup
        caches:
        - node
        script:
        - yarn
        - yarn build
        - tar czfv application.tgz build
        artifacts:
        - application.tgz
    - step:
        name: Deploy
        script:
        - pipe: atlassian/heroku-deploy:0.1.2
          variables:
            HEROKU_API_KEY: "112c6fb6-2bdb-4787-98a8-6941352cbea9"
            HEROKU_APP_NAME: "cmadminportal"
            ZIP_FILE: "application.tgz"
